@startuml
class GameObject {
    + IsDead : bool <<get>> <<set>>
    + Radius : float <<get>> <<set>>
    + Rotation : float <<get>> <<set>>
    + CollidesWith(other:IGameObject) : bool
}
class Meteor {
    + ExplotionScale : float <<get>> <<set>>
    + Meter(type:MeteorType) : void
    + Update(gametime:GameTime) : void
    + BreakMeteor(meteor:Meteor) : IEnumerable<Meteor>
}
class MeteorType {
}
class GameTime {
}
interface IGameObject {
}
GameObject --> "Position" Vector2
GameObject --> "Speed" Vector2
GameObject <|-- Meteor
Meteor --> "Type" MeteorType
GameObject +-- IGameObject
@enduml
